drop table ESPORTE cascade constraints;
drop table CAMPEONATO cascade constraints;
drop table USUARIO cascade constraints;
drop table CLUBE cascade constraints;
drop table ROTEIROVIAGEM cascade constraints;
drop table HOSPEDAGEM cascade constraints;
drop table TRANSPORTE cascade constraints;
drop table TIME cascade constraints;
drop table PARTIDA cascade constraints;
drop table PARTIDATIME cascade constraints;
drop table PONTOTURISTICO cascade constraints;
drop table TREINADORESTIME cascade constraints;
drop table ATLETATIME cascade constraints;
drop table USUARIOACOMPANHAESPORTE cascade constraints;
drop table USUARIOTORCE cascade constraints;
drop table ROTEIROPONTOTURISTICO cascade constraints;
drop table ROTEIROTRANSPORTE cascade constraints;
drop table ROTEIROPARTIDA cascade constraints;
drop sequence SEQ_ID_CLUBE;
drop sequence SEQ_ID_TIME;